import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LandingPageOne</Link>
        </li>
        <li>
          <Link to="/signinpage">SignInPage</Link>
        </li>
        <li>
          <Link to="/homepageone">HomepageOne</Link>
        </li>
        <li>
          <Link to="/searchpage">Searchpage</Link>
        </li>
        <li>
          <Link to="/fashionviewpage">Fashionviewpage</Link>
        </li>
        <li>
          <Link to="/saveditemspage">SavedItemspage</Link>
        </li>
        <li>
          <Link to="/notificationspage">Notificationspage</Link>
        </li>
        <li>
          <Link to="/profile">PROFILE</Link>
        </li>
        <li>
          <Link to="/signup">SignUp</Link>
        </li>
        <li>
          <Link to="/notificationsviewpage">NotificationsViewpage</Link>
        </li>
        <li>
          <Link to="/landingpagetwo">LandingPageTwo</Link>
        </li>
        <li>
          <Link to="/chooseyouravatarupdaed">CHOOSEYOURAVATARupdaed</Link>
        </li>
        <li>
          <Link to="/chooseyouravatarsuccess">CHOOSEYOURAVATARSUCCESS</Link>
        </li>
        <li>
          <Link to="/logoutscreen">Logoutscreen</Link>
        </li>
        <li>
          <Link to="/landingpagethree">LandingPageThree</Link>
        </li>
        <li>
          <Link to="/community">Community</Link>
        </li>
        <li>
          <Link to="/fashionistacommunity">FashionistaCommunity</Link>
        </li>
        <li>
          <Link to="/landingpagefour">LandingPageFour</Link>
        </li>
        <li>
          <Link to="/reward">Reward</Link>
        </li>
        <li>
          <Link to="/landingpagefive">LandingPageFive</Link>
        </li>
        <li>
          <Link to="/menuextenderview">MENUEXTENDERVIEW</Link>
        </li>
        <li>
          <Link to="/homepage">Homepage</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
